# frozen_string_literal: true

class Home < Porous::Page
  metadata route: '/', title: 'Porous • Home',
           description: 'Landing page generated by Porous'

  # rubocop:disable Metrics, Layout/LineLength
  def content
    body class: 'container p-8 mx-auto lg:h-full xl:px-0 flex flex-wrap' do
      div class: 'flex items-center w-full lg:w-1/2' do
        div class: 'max-w-2xl mb-8' do
          h1 class: 'text-4xl font-bold leading-snug tracking-tight text-gray-800 lg:text-4xl lg:leading-tight xl:text-6xl xl:leading-tight dark:text-white' do
            span 'Welcome to Porous!', class: 'bg-gradient-to-br from-pink-500 to-violet-500 bg-clip-text text-transparent box-decoration-clone'
          end
          p class: 'py-5 text-xl leading-normal text-gray-500 lg:text-xl xl:text-2xl dark:text-gray-300' do
            text 'Porous is an all-in-one application engine for building applications with Web technologies.'
          end

          div class: 'flex flex-col items-start space-y-3 sm:space-x-4 sm:space-y-0 sm:items-center sm:flex-row' do
            a href: 'https://github.com/exastencil/porous', target: '_blank', rel: 'noopener',
              class: 'group relative inline-flex h-12 items-center justify-center overflow-hidden rounded-md bg-indigo-600 px-6 font-medium text-neutral-200 transition hover:scale-110' do
              span 'Get Started 🧽'
              div class: 'absolute inset-0 flex h-full w-full justify-center [transform:skew(-12deg)_translateX(-100%)] group-hover:duration-1000 group-hover:[transform:skew(-12deg)_translateX(100%)]' do
                div class: 'relative h-full w-8 bg-white/20'
              end
            end
            a href: 'https://github.com/exastencil/porous', target: '_blank', rel: 'noopener',
              class: 'flex items-center space-x-2 text-gray-500 dark:text-gray-400' do
              # GitHub icon
              svg class: 'w-8 h-8 text-gray-500', xmlns: 'http://www.w3.org/2000/svg', viewBox: '0 -0.5 24 24' do
                path fill_rule: 'evenodd', clip_rule: 'evenodd',
                     d: 'M12.2047 0.00001C6.56031 -0.005731 1.74628 4.08615 0.842541 9.6577C-0.061195 15.2293 3.2126 20.6331 8.56941 22.4118C9.14823 22.5177 9.35294 22.1577 9.35294 21.8541C9.35294 21.5506 9.35294 20.8588 9.35294 19.8988C6.14117 20.5977 5.46353 18.3529 5.46353 18.3529C5.25046 17.6572 4.79779 17.0595 4.18588 16.6659C3.14823 15.96 4.27059 15.96 4.27059 15.96C5.00761 16.0641 5.65578 16.5014 6.02823 17.1459C6.34368 17.7179 6.87393 18.1406 7.50179 18.3208C8.12965 18.5009 8.8034 18.4236 9.37411 18.1059C9.41842 17.5252 9.66876 16.9794 10.08 16.5671C7.5247 16.2777 4.84235 15.2894 4.84235 10.92C4.82481 9.7786 5.24688 8.67412 6.02117 7.8353C5.67632 6.84285 5.71662 5.7571 6.13412 4.79295C6.13412 4.79295 7.10117 4.48236 9.29647 5.97177C11.1816 5.45419 13.1713 5.45419 15.0565 5.97177C17.2518 4.48236 18.2118 4.79295 18.2118 4.79295C18.6351 5.74689 18.6854 6.82486 18.3529 7.81412C19.1272 8.65294 19.5493 9.7574 19.5318 10.8988C19.5318 15.3177 16.8424 16.2847 14.28 16.5459C14.8359 17.1047 15.1218 17.8774 15.0635 18.6635C15.0635 20.2024 15.0635 21.4447 15.0635 21.8188C15.0635 22.1929 15.2682 22.4824 15.8541 22.3694C21.1473 20.5447 24.3569 15.1728 23.4554 9.6469C22.5539 4.1211 17.8034 0.04779 12.2047 0.00001z'
              end
              span 'View on GitHub'
            end
          end
        end
      end

      div class: 'flex items-center justify-center w-full lg:w-1/2' do
        div do
          img src: '/hero.png', width: '616', height: '617', class: 'object-cover', alt: 'Hero Illustration'
        end
      end
    end

    script src: 'https://cdn.tailwindcss.com'
  end
  # rubocop:enable Metrics, Layout/LineLength
end
